trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- task: Npm@1
  inputs:
    command: install
    customRegistry: useFeed
    customFeed : botas/botas-upstream
    verbose: true
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm build'

- script: node setVersion.js
  displayName: 'node setVersion.js'

- task: Npm@1
  inputs:
    command: custom
    customCommand: publish --workspaces
    publishRegistry: useFeed
    publishFeed : botas/botas-dev
    verbose: true
  displayName: 'npm publish'

