# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: echo "registry=https://pkgs.dev.azure.com/rmpablos/botas/_packaging/botas-nightly/npm/registry/" > .npmrc
  displayName: 'Create .npmrc'

# - task: npmAuthenticate@0
#   inputs:
#     workingFile: $(agent.tempdirectory)/.npmrc

# - script: 
#     cat $(agent.tempdirectory)/.npmrc
#   displayName: 'cat .npmrc in agenttempdir'

- script: npm install -g vsts-npm-auth --registry https://registry.npmjs.org
  displayName: 'install vsts-npm-auth'

- script: vsts-npm-auth -config .npmrc -V Detailed -N
  displayName: 'vsts-npm-auth'

- script: 
    type C:\Users\VssAdministrator\.npmrc
  displayName: 'type .npmrc'

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm build'

- script: npm publish --workspaces  --registry https://pkgs.dev.azure.com/rmpablos/botas/_packaging/botas-nightly/npm/registry/
  displayName: 'push to azdo'

# - task: Npm@1
#   inputs:
#     command: custom
#     publishRegistry: useFeed
#     customCommand: publish --workspaces --registry https://pkgs.dev.azure.com/rmpablos/botas/_packaging/botas-nightly/npm/registry
#     publishFeed : botas/botas-nightly
#   displayName: 'npm publish'

