name: CD

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@botas'

      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

